### PR TITLE
fixed compilation issues related to recent changes in inspector-metrics

### PR DESCRIPTION
**Pull request by doubret**
Library had to be updated due to recent changes in inspector-metrics (return this pattern and Scheduler signature changes)

### CODE REVIEW

**Comment by rstiller** [comment]
Thaks again. I'll publish it asap.

**Comment by doubret** [comment]
Sorry to contribute a lot...
Hope it's not too much time consuming on your side.

**Comment by rstiller** [comment]
No worries :)
I think it good for the lib to get used by more people.

**Comment by doubret** [comment]
Great, i have made another pull request ;)

**Pull request merged**
